-- CONSULTATIONS
CREATE TABLE `CONSULTATIONS` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `CONSULTATION_DATE` DATE NOT NULL,
  `CONSULTATION_STATUS` VARCHAR(255) NOT NULL,
  `CONSULTATION_TIME` TIME DEFAULT NULL,
  `PATIENT_UUID` VARCHAR(50) NOT NULL,
  `CONSULTATION_TYPE_ID` BIGINT(20) NOT NULL,
  `DOCTOR_ID` BIGINT(20) NOT NULL,
  `HEALTH_FACILITY_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CONSULTATIONS_CONSULTATION_TYPE_ID` (`CONSULTATION_TYPE_ID`),
  KEY `FK_CONSULTATIONS_DOCTOR_ID` (`DOCTOR_ID`),
  KEY `FK_CONSULTATIONS_HEALTH_FACILITY_ID` (`HEALTH_FACILITY_ID`),
  CONSTRAINT `FK_CONSULTATIONS_CONSULTATION_TYPE_ID` FOREIGN KEY (`CONSULTATION_TYPE_ID`) REFERENCES `CONSULTATION_TYPES` (`ID`),
  CONSTRAINT `FK_CONSULTATIONS_DOCTOR_ID` FOREIGN KEY (`DOCTOR_ID`) REFERENCES `DOCTORS` (`ID`),
  CONSTRAINT `FK_CONSULTATIONS_HEALTH_FACILITY_ID` FOREIGN KEY (`HEALTH_FACILITY_ID`) REFERENCES `HEALTH_FACILITIES` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;