-- DOCTOR_MEDICAL_SERVICE_TYPE
CREATE TABLE `DOCTOR_MEDICAL_SERVICE_TYPE` (
  `DOCTOR_ID` BIGINT(20) NOT NULL,
  `MEDICAL_SERVICE_TYPE_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`DOCTOR_ID`,`MEDICAL_SERVICE_TYPE_ID`),
  KEY `FK_DOCTOR_MEDICAL_SERVICE_TYPE_ID` (`MEDICAL_SERVICE_TYPE_ID`),
  CONSTRAINT `FK_DOCTOR_MEDICAL_SERVICE_TYPE_ID` FOREIGN KEY (`MEDICAL_SERVICE_TYPE_ID`) REFERENCES `MEDICAL_SERVICE_TYPES` (`ID`),
  CONSTRAINT `FK_DOCTOR_ID_MEDICAL_SERVICE_TYPE` FOREIGN KEY (`DOCTOR_ID`) REFERENCES `DOCTORS` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;