-- DOCTOR_CONSULTATION_TYPE
CREATE TABLE `DOCTOR_CONSULTATION_TYPE` (
  `DOCTOR_ID` BIGINT(20) NOT NULL,
  `CONSULTATION_TYPE_ID` BIGINT(20) NOT NULL,
  PRIMARY KEY (`DOCTOR_ID`,`CONSULTATION_TYPE_ID`),
  KEY `FK_DOCTOR_CONSULTATION_TYPE_ID` (`CONSULTATION_TYPE_ID`),
  CONSTRAINT `FK_DOCTOR_CONSULTATION_TYPE_ID` FOREIGN KEY (`CONSULTATION_TYPE_ID`) REFERENCES `CONSULTATION_TYPES` (`ID`),
  CONSTRAINT `FK_DOCTOR_ID_CONSULTATION_TYPE` FOREIGN KEY (`DOCTOR_ID`) REFERENCES `DOCTORS` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;