-- HEALTH FACILITIES
CREATE TABLE `CONSULTATION_TYPES` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CREATED_AT` DATETIME NOT NULL,
  `CREATED_BY` VARCHAR(50) NOT NULL,
  `ENTITY_STATUS` VARCHAR(15) NOT NULL,
  `UPDATED_AT` DATETIME DEFAULT NULL,
  `UPDATED_BY` VARCHAR(50) DEFAULT NULL,
  `UUID` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(150) NOT NULL,
  `LOCALITY_UUID` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50),
  `PHONE_NUMBER` VARCHAR(20) NOT NULL,
  `PHONE_NUMBER_OPTIONAL` VARCHAR(20),
  `IMAGE_PATH` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8;